<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EILS56310BWP8TT" ignored="0" name="Command line test" tests="4" failures="1" timestamp="21 十一月 2018 06:32:52 GMT" time="1.316" errors="0">
  <testcase name="test" time="0.001" classname="test.UtilsMethodTest"/>
  <testcase name="testJsonUtils" time="0.174" classname="test.UtilsMethodTest">
    <skipped/>
  </testcase> <!-- testJsonUtils -->
  <testcase name="testJsonUtils" time="0.001" classname="test.UtilsMethodTest">
    <skipped/>
  </testcase> <!-- testJsonUtils -->
  <testcase name="testJsonUtils" time="0.001" classname="test.UtilsMethodTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at test.UtilsMethodTest.testJsonUtils(UtilsMethodTest.java:46)
at test.UtilsMethodTest.main(UtilsMethodTest.java:64)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testJsonUtils -->
</testsuite> <!-- Command line test -->
